const path = require('path');

const { headers } = require('next/headers');

process.env.NODE_ENV = 'production';
process.env.PORT = process.env.PORT || 3000;
process.env.HOSTNAME = '0.0.0.0';

// Point to the standalone server generated by Next.js
// Note: Ensure you have run 'npm run build' first
require('./.next/standalone/server.js');
